[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia = "https://sepolia.infura.io/v3/6766b1e75f984f5d8ae70814899ba348", arb-sepolia = "https://arbitrum-sepolia.infura.io/v3/6766b1e75f984f5d8ae70814899ba348" }
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink/local/=lib/chainlink-local/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
